version: '3.8'

services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api_c
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017